// Generated by build_gh3_hold.py; matches hold_hook.bin.
static class Payload {
 public const long Hook = 0x430F71, Return = 0x430F77, RoutineStart = 0x430780;
 public const int RoutineSize = 4490, FlagRelocation = 15, ReturnRelocation = 284;
 public const long MissHook = 0x430610;
 public const int MissOffset = 0x200;
 public static readonly int[] FlagRelocations = new int[]{15,527}, ReturnRelocations = new int[]{284,660};
 public static readonly long[] ReturnTargets = new long[]{0x430f77,0x430616};
 public static readonly byte[] MissOriginal = new byte[]{0x55,0xbd,1,0,0,0};
 public const string MissRoutineHash = "de04ee7b9b1bddc1e24e81311f2944f51083e239f06579654264ecaaf070884c";
 public const string ExeHash = "801f8a522651a479d63a9ff5fbde5be949ba0b7ad2ec0e5fb1d92ab1a8ef2154", RoutineHash = "aa2c1c62d61e52a0a0b8f9f77c24002b47377823049dc787c3bc63f3102a9e16";
 public static readonly byte[] Original = new byte[]{0x8b,0x4c,0x24,0x28,0x85,0xc9};
}
